mysql_local_host = "localhost"
mysql_database = "sales"
mysql_user = "root"
mysql_pass = ""
table_products = "products"

meniu_option1 = "List products"
meniu_option2 = "Update Quantity"
meniu_option3 = "Add product"
meniu_option4 = "Change name"
meniu_option5 = "Delete product"
meniu_option6 = "List product types"
meniu_option7 = "Exit"